language: cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
env:
  matrix:
  - PACKAGER_NODE_VERSION="0.10" PACKAGER_ARCH="amd64"
  - PACKAGER_NODE_VERSION="0.10" PACKAGER_ARCH="386"
  - PACKAGER_NODE_VERSION="0.12" PACKAGER_ARCH="amd64"
  - PACKAGER_NODE_VERSION="0.12" PACKAGER_ARCH="386"
  - PACKAGER_NODE_VERSION="4" PACKAGER_ARCH="amd64"
  - PACKAGER_NODE_VERSION="4" PACKAGER_ARCH="386"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD=true
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="0.10" PACKAGER_ARCH="386"
  - os: osx
    env: PACKAGER_NODE_VERSION="0.12" PACKAGER_ARCH="386"
  - os: osx
    env: PACKAGER_NODE_VERSION="4" PACKAGER_ARCH="386"
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
before_install:
- curl -fsS "https://meshblu-connector.octoblu.com/tools/packager/v6.0.2/travis_install_node.sh" | bash
install:
- npm install --build-from-source
script:
- npm test
before_deploy:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PACKAGER_OS="darwin"; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PACKAGER_OS="linux"; fi
- if [ "$TRAVIS_OS_NAME" == "linux" && "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH=true; fi
- export PACKAGER_CONNECTOR="bean"
- export PACKAGER_TAG="$TRAVIS_TAG"
- curl -fsS "https://meshblu-connector.octoblu.com/tools/packager/v6.0.2/build.sh" | bash
code_climate:
  repo_token: "d220cd4236a5f28ed7eaa865f718b4f81fa22d988644a89b3589bc019c70da1b"
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "BRUrPTH9jLWLpTQ0bnOKOWtbjgG45XM8MyqE70ldB7pnFkwzUDhcNT4BhLkut2iE8l/ja78iGGZDDraN7wML686u6NoomRsaamL8oH0VneTpuqSAaY0S4TI0pmi0Z6jhd819jBCf4E4WXDOo7RJ7COg4dmAb+A/xyorq3PJkzAazZB9b+CM2fSFUHdGvste/pGL8bzkPJ4Y9Celdd1urWpq48B9ZM8CqI36/M+jRw1IhoXGtt1cY03g20pVCnUCQ38mwsAG+liEaIoI6KUFkfyb2Tdw71rScajLvSyW1H+zMRjn6/xpc4I7CWV2iZjaUgB2Knl449v5HNSGynf2rNG1DFfk1Phb/eiv8Z33rRyh5Q5W1XB9Cpy4YQOZq4pYJetIVH4aDGzPOyKOBUInYOsYzlR0ZP+FkkbCKoKa4cbzRpEqJId5jIbD72gecB/zEE/468vSKXeDZ0vQLrpL/kK9DYqsu8AawALcnI+a+RLUs6QgTOJ4wu4b2Qn+6lrnId8wHicZvsB3vqweH5rZrKnmtsLILwxlr283hOLVrlu9tJDhrDVIwEqS4FltNo6+ebCVeESFhrUB75FDBlX/w4M+nmLrHbEhKoBPgdmEGgNAxQbtm2ucN06ned3NY5zCMnxeGDGCablk7Oaliir9TzfbH4eNHjFT54M0HVONn3HA="
  bucket: meshblu-connector
  local-dir: deploy
  upload-dir: connectors
  region: us-west-2
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: yp+gaExXvHlY5rpvq+4f1eySA2xHrr6RSNN2+HZFFYcR5Pb9lkYMQv9ydLbQwhHmDG1gFbV9cdmqtUMvnoKE3+6F7ztlJH3G2UeXtW6TlrJMq5+PJ+Eeeu6XX+FuLHKirMDO3fxGGCBMvrgMP4r/jsjaRbgzKQHI5BiGWN4+xBpseNPaG9+msp+GofVZAJikN7s6bIgR8SQbwHz56ZpThBWN3goKtOmwq0+FzDiIkrfGfjLxL57QSBwSurPhN2gclvuGn6HBJHV0oUT0WjVEA5oJCpQmtybjsezhJXvHwSIaLlIzAJ0Mw8wZr8fvUaYKaxVJM3WVv9763iGYNxXb/LKltsMkWp2cSHpDw5Fq6U5cD0bo6GBZYdNh3nXqKU+bfh7h+1GVwj4PhwISe0yXbU0uXaKDN3Fd3+1ls1RAd++a3suWKaJDe/W/REkkzZif3wrMfQ2z1uQ2byGJNeXeuKS0DiYg0H+U4eU8reIRsO1ByV4y+YUK74vIicp7qeibXDHJ8DfnBv7ErFdKskDQGTi7inQRRhp4PE3iOglq1hC3TEWEgkGOshp+cVOOWsniyWOSgA4Y9tSZBRnaPkw0XYvAiE0svop5BjxIrQAw8zCXHgcfN7SKOJs4bM3DwFKKk3gX+je3coyc3Y73goUyk1geAKX49bzssuNYmZjXRPo=
  on:
    tags: true
    condition: "$NPM_PUBLISH=true"
