sudo: required
language: cpp
os:
- linux
- osx
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libbluetooth-dev
    - libudev-dev
    - g++-4.8
  code_climate:
    repo_token: "d220cd4236a5f28ed7eaa865f718b4f81fa22d988644a89b3589bc019c70da1b"
before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install opencv; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install nvm; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then source $(brew --prefix nvm)/nvm.sh; fi
- export PATH=./node_modules/.bin/:$PATH
- nvm install 5.5
- npm install -g npm
install:
- npm install
before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then npm install -g codeclimate-test-reporter fi;
script:
- npm test
after_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then codeclimate-test-reporter < coverage/lcov.info; fi
before_deploy:
- curl -fsS https://meshblu-connector.octoblu.com/tools/packager/v4.0.0/build.sh -o .build.sh
- chmod +x ./.build.sh
- ./.build.sh bean ${TRAVIS_TAG:-$TRAVIS_COMMIT} $TRAVIS_OS_NAME
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "BRUrPTH9jLWLpTQ0bnOKOWtbjgG45XM8MyqE70ldB7pnFkwzUDhcNT4BhLkut2iE8l/ja78iGGZDDraN7wML686u6NoomRsaamL8oH0VneTpuqSAaY0S4TI0pmi0Z6jhd819jBCf4E4WXDOo7RJ7COg4dmAb+A/xyorq3PJkzAazZB9b+CM2fSFUHdGvste/pGL8bzkPJ4Y9Celdd1urWpq48B9ZM8CqI36/M+jRw1IhoXGtt1cY03g20pVCnUCQ38mwsAG+liEaIoI6KUFkfyb2Tdw71rScajLvSyW1H+zMRjn6/xpc4I7CWV2iZjaUgB2Knl449v5HNSGynf2rNG1DFfk1Phb/eiv8Z33rRyh5Q5W1XB9Cpy4YQOZq4pYJetIVH4aDGzPOyKOBUInYOsYzlR0ZP+FkkbCKoKa4cbzRpEqJId5jIbD72gecB/zEE/468vSKXeDZ0vQLrpL/kK9DYqsu8AawALcnI+a+RLUs6QgTOJ4wu4b2Qn+6lrnId8wHicZvsB3vqweH5rZrKnmtsLILwxlr283hOLVrlu9tJDhrDVIwEqS4FltNo6+ebCVeESFhrUB75FDBlX/w4M+nmLrHbEhKoBPgdmEGgNAxQbtm2ucN06ned3NY5zCMnxeGDGCablk7Oaliir9TzfbH4eNHjFT54M0HVONn3HA="
  bucket: meshblu-connector
  local-dir: deploy
  upload-dir: connectors
  region: us-west-2
  skip_cleanup: true
  on:
    tags: true
    branches: true
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: yp+gaExXvHlY5rpvq+4f1eySA2xHrr6RSNN2+HZFFYcR5Pb9lkYMQv9ydLbQwhHmDG1gFbV9cdmqtUMvnoKE3+6F7ztlJH3G2UeXtW6TlrJMq5+PJ+Eeeu6XX+FuLHKirMDO3fxGGCBMvrgMP4r/jsjaRbgzKQHI5BiGWN4+xBpseNPaG9+msp+GofVZAJikN7s6bIgR8SQbwHz56ZpThBWN3goKtOmwq0+FzDiIkrfGfjLxL57QSBwSurPhN2gclvuGn6HBJHV0oUT0WjVEA5oJCpQmtybjsezhJXvHwSIaLlIzAJ0Mw8wZr8fvUaYKaxVJM3WVv9763iGYNxXb/LKltsMkWp2cSHpDw5Fq6U5cD0bo6GBZYdNh3nXqKU+bfh7h+1GVwj4PhwISe0yXbU0uXaKDN3Fd3+1ls1RAd++a3suWKaJDe/W/REkkzZif3wrMfQ2z1uQ2byGJNeXeuKS0DiYg0H+U4eU8reIRsO1ByV4y+YUK74vIicp7qeibXDHJ8DfnBv7ErFdKskDQGTi7inQRRhp4PE3iOglq1hC3TEWEgkGOshp+cVOOWsniyWOSgA4Y9tSZBRnaPkw0XYvAiE0svop5BjxIrQAw8zCXHgcfN7SKOJs4bM3DwFKKk3gX+je3coyc3Y73goUyk1geAKX49bzssuNYmZjXRPo=
  on:
    condition: "$TRAVIS_OS_NAME = linux"
    tags: true
    branches: true
